create database join1;
use join1;
create table student(
STUDENTID INT,
NAME VARCHAR(20),
EMAIL VARCHAR(50),
PERCENTAGE INT,
DEPARTMENTID INT);

INSERT INTO STUDENT VALUES
(1001,'AJAY','AJAY@XYZ.COM',85,1),
(1002,'BABLOO','BABLOO@XYZ.COM',67,2),
(1003,'CHHAVI','CHHAVI@XYZ.COM',89,3),
(1004,'DHEERAJ','DHEERAJ@XYZ.COM',75,4),
(1005,'EVINA','EVINA@XYZ.COM',91,1),
(1006,'KRISHNA','KRISHNA@XYZ.COM',99,5);

CREATE TABLE DEPARTMENT(
DEPARTMENTID INT,
DEPARTMENTNAME VARCHAR(20));

INSERT INTO DEPARTMENT VALUES
(1,'MATHEMATICS'),
(2,'PHYSICS'),
(3,'ENGLISH');

CREATE TABLE FACULTY
(DEPARTMENTID INT,
FACULTYNAME VARCHAR(20));

INSERT INTO FACULTY VALUES
(1,'PIYUSH'),
(2,'NAMITA'),
(3,'ASHNEER'),
(4,'GHAZAI'),
(5,'ANUPAM');

SELECT S.STUDENTID ,S.NAME,S.EMAIL,S.PERCENTAGE,S.DEPARTMENTID,F.FACULTYNAME
FROM STUDENT s
INNER JOIN FACULTY F ON
S.DEPARTMENTID=F.DEPARTMENTID;

SELECT S.NAME,S.STUDENTID,F.FACULTYNAME,S.DEPARTMENTID
FROM STUDENT S
LEFT JOIN FACULTY F ON
S.DEPARTMENTID=F.DEPARTMENTID WHERE F.FACULTYNAME='PIYUSH' OR F.FACULTYNAME='ASHNEER';


SELECT S.NAME,S.STUDENTID,F.FACULTYNAME,S.DEPARTMENTID,D.DEPARTMENTNAME
FROM STUDENT S
INNER JOIN DEPARTMENT D ON
D.DEPARTMENTID=S.DEPARTMENTID
RIGHT JOIN FACULTY F ON
F.DEPARTMENTID=D.DEPARTMENTID;


use world;

select * from city;

select *FROM COUNTRY;

/*Given the CITY and COUNTRY tables, query the sum of the populations of all cities
where the CONTINENT is 'ASIA'.

2. Given the CITY and COUNTRY tables, query the names of all cities where
the CONTINENT is 'AFRICA;.
Given the CITY and COUNTRY tables, query the names of all the continents
3. (COUNTRY. Continent) and their respective average city populations (CITY. Population)
rounded down to the nearest integer.
Note: CITY.CountryCode and COUNTRY.Code are matching key columns.*/


SELECT A.NAME,C.POPULATION,C.CONTINENT,A.DISTRICT FROM CITY A
INNER JOIN COUNTRY C ON
A.NAME=C.NAME WHERE CONTINENT='ASIA';

SELECT A.NAME,C.POPULATION,C.CONTINENT,A.DISTRICT FROM CITY A
INNER JOIN COUNTRY C ON
A.NAME=C.NAME WHERE CONTINENT='AFRICA';

SELECT C.Continent,
    ROUND(AVG(A.Population)) AS Average_Population
FROM COUNTRY C
JOIN CITY A ON C.Code = A.CountryCode
GROUP BY C.Continent;

CREATE TABLE STUDENTS(
ID INT,
NAME VARCHAR(20),
 MARKS INT);
 
INSERT INTO STUDENTS VALUES
(1,'JULIA',88),
(2,'SAMANTHA',68),
(3,'MARIA',99),
(4,'SCARLET',78),
(5,'ASHLEY',63),
(6,'JANE',81);

CREATE TABLE GRADES(
GRADE INT,
MIN_MARK INT,
MAX_MARK INT);

INSERT INTO GRADES VALUES
(1,0,9),
(2,10,19),
(3,20,29),
(4,30,39),
(5,40,49),
(6,50,59),
(7,60,69),
(8,70,79),
(9,80,89),
(10,90,100);

alter table STUDENTS
add column GRADES1 VARCHAR(20) ;
UPDATE STUDENTS SET GRADES1=IF((MARKS>=90,10,

IF((MARKS>=80,9,

IF((MARKS>=70,8,'NULL'))));


SELECT
    CASE 
        WHEN MARKS >= 8 THEN S.Name 
        ELSE 'NULL' 
    END AS GRADES1
    
    FROM STUDENTS S;
S.NAME,S.MarkS,S.ID FROM Students S
ORDER BY MARKS DESC, 
    CASE 
        WHEN MARKS >= 8 THEN S.Name 
        ELSE S.MarkS 
    END AS GRADES1;

SELECT * FROM STUDENTS;