use sakila;

CREATE DATABASE JOIN_3;
USE JOIN_3;

CREATE TABLE STUDENT(
S_ID INT PRIMARY KEY,
S_NAME VARCHAR(20));

INSERT INTO STUDENT VALUES(1,'JACK'),
(2,'RITHVIK'),
(3,'JASPREET'),
(4,'PRAVEEN'),
(5,'BISA'),
(6,'SURAJ');

CREATE TABLE MARKS(
SCHOOL_ID INT PRIMARY KEY,
S_ID INT, SCORE INT,
STATUS VARCHAR(20));

INSERT INTO MARKS VALUES(1004,1,23,'FAIL'),
(1008,6,95,'PASS'),
(1012,2,97,'PASS'),
(1016,7,67,'PASS'),
(1020,3,100,'PASS'),
(1025,8,73,'PASS'),
(1030,4,88,'PASS'),
(1035,9,13,'FAIL'),
(1040,5,16,'FAIL'),
(1050,10,53,'PASS');

SELECT * FROM MARKS;

CREATE TABLE DETAILS(
ADDRESS_CITY VARCHAR(20),
EMAIL_ID VARCHAR(20),
SCHOOL_ID INT,
ACCOMPLISHMENTS VARCHAR(50));

INSERT INTO DETAILS VALUES
('BANGALORE','JSINGH@JTP.COM',1020,'ACM ICPC SELECTED'),
('HYDERABAD','PRAVEEN@JTP.COM',1030,'GEEK OF THE MONTH'),
('DELHI','TITHVIK@JTP.COM',1012,'IOI FINALIST'),
('CHENNAI','OM@JTP.COM',1111,'GEEK OF THE YEAR'),
('BANGALORE','SURAJ@JTP.COM',1008,'IMO FINALIST'),
('MUMBAI','SASUKEH@JTP.COM',2211,'MADE A ROBOT'),
('AHMEDABAD','ITACHI@JTP.COM',1172,'CODE JAM FINALIST'),
('JAIPUR','KUMAR@JTP.COM',1972,'KVPY FINALIST');

SELECT S.S_ID,S_NAME,SCORE,STATUS,ADDRESS_CITY,EMAIL_ID,ACCOMPLISHMENTS
FROM STUDENT s
INNER JOIN MARKS M ON
S.S_ID=M.S_ID
INNER JOIN
DETAILS D ON
D.SCHOOL_ID=M.SCHOOL_ID;


SELECT * FROM DETAILS;
SELECT * FROM STUDENT;


DROP TABLE MODE_OF_STAY;
CREATE TABLE MODE_OF_STAY(
ADDRESS_CITY VARCHAR(20),
MODE_OF_STAY VARCHAR(20));

INSERT INTO MODE_OF_STAY VALUES
('BANGALORE','PG'),
('HYDERABAD','HOSTEL'),
('DELHI','HOSTEL'),
('CHENNAI','DAYSCHOLAR'),
('BANGALORE','PG'),
('MUMBAI','PG'),
('AHMEDABAD','DAYSCHOLAR'),
('JAIPUR','HOSTEL');

SELECT * FROM MODE_OF_STAY;

SELECT S.S_ID,S_NAME,SCORE,STATUS,Y.ADDRESS_CITY,EMAIL_ID,ACCOMPLISHMENTS,MODE_OF_STAY
FROM STUDENT s
INNER JOIN MARKS M ON
S.S_ID=M.S_ID
INNER JOIN
DETAILS D ON
D.SCHOOL_ID=M.SCHOOL_ID
RIGHT JOIN MODE_OF_STAY Y ON D.ADDRESS_CITY=Y.ADDRESS_CITY;

SELECT * FROM MODE_OF_STAY;

use join_3;
