SHOW DATABASES;
USE SAKILA;
SELECT * FROM CUSTOMER;
SELECT FIRST_NAME,LAST_NAME FROM CUSTOMER;
SELECT * FROM CUSTOMER LIMIT 5;
SELECT COUNT(*) FROM CUSTOMER;
SELECT DISTINCT(ACTIVE) FROM CUSTOMER;
SELECT DISTINCT(STORE_ID) FROM CUSTOMER;
SELECT * FROM CUSTOMER WHERE FIRST_NAME='MARY';
SELECT STORE_ID,LAST_NAME,EMAIL FROM CUSTOMER WHERE FIRST_NAME='MARIA';
SELECT * FROM CUSTOMER WHERE ACTIVE=0;
SELECT * FROM CUSTOMER WHERE ADDRESS_ID=451;
SELECT FIRST_NAME,LAST_NAME,EMAIL FROM CUSTOMER WHERE ADDRESS_ID=540;
SELECT * FROM CUSTOMER WHERE ADDRESS_ID<=20;
SELECT * FROM CUSTOMER WHERE FIRST_NAME='LISA';
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID BETWEEN 20 AND 25;
SELECT  * FROM CUSTOMER WHERE FIRST_NAME='IAN' OR LAST_NAME='STILER';
SELECT * FROM CUSTOMER WHERE FIRST_NAME='AMY' AND LAST_NAME='LOPEZ';
SELECT * FROM CUSTOMER;
UPDATE CUSTOMER SET FIRST_NAME='VIJAYA' WHERE LAST_NAME='SMITH';
SELECT * FROM CUSTOMER WHERE FIRST_NAME='VIJAYA';
SELECT FIRST_NAME,LAST_NAME,ADDRESS_ID FROM CUSTOMER ORDER BY FIRST_NAME DESC;
SELECT FIRST_NAME,LAST_NAME,ADDRESS_ID FROM CUSTOMER ORDER BY ADDRESS_ID ASC;  /* DEFAULT IT GIVES ASCENDING ORDER */
SELECT STORE_ID,ADDRESS_ID FROM CUSTOMER WHERE STORE_ID=1 ORDER BY ADDRESS_ID DESC LIMIT 3;
SELECT MIN(ADDRESS_ID)FROM CUSTOMER;
SELECT MAX(ADDRESS_ID) FROM CUSTOMER;
SELECT SUM(ADDRESS_ID) FROM CUSTOMER;
SELECT AVG(ADDRESS_ID) FROM CUSTOMER;
SELECT COUNT(ADDRESS_ID) FROM CUSTOMER;
SELECT FIRST_NAME FROM CUSTOMER ORDER BY ADDRESS_ID ASC LIMIT 1;
SELECT FIRST_NAME, LAST_NAME FROM CUSTOMER WHERE ADDRESS_ID =(SELECT MIN(ADDRESS_ID)  FROM CUSTOMER);
select fIRST_NAME,LAST_NAME,ADDRESS_ID FROM CUSTOMER WHERE ADDRESS_ID=(SELECT MIN(ADDRESS_ID) FROM CUSTOMER);
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'R%';
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE '%A';
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'J%A'; /* START WITH J AND END WITH A */
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE '%NI%'; /* INBETWEEN CHARC */
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'A______%'; /* FIRST_NAME SHOULD BE START WITH A AND MORE THAN 6 AND ENDLESS CHAR */
SELECT * FROM CUSTOMER WHERE LENGTH(FIRST_NAME)=5;
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'A____';  
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'A%' AND LENGTH(FIRST_NAME)=5;
SELECT * FROM CUSTOMER WHERE CUSTOMER_ID IN (1,2,3);
SELECT * FROM CUSTOMER WHERE CUSTOMER_ID NOT IN(1,2,3);
SELECT FIRST_NAME AS FIRST,LAST_NAME AS LAST FROM CUSTOMER;  /*CHANGE CLOUMN NAME FOR TEMP */
SELECT STORE_ID,COUNT(STORE_ID) FROM CUSTOMER GROUP BY STORE_ID; 
USE WORLD;
SELECT * FROM COUNTRY;
SELECT DISTINCT(CONTINENT) FROM COUNTRY;
SELECT SURFACEAREA, CONTINENT FROM COUNTRY WHERE SURFACEAREA=(SELECT MAX(SURFACEAREA) FROM COUNTRY);
SELECT SUM(POPULATION),CONTINENT FROM COUNTRY GROUP BY CONTINENT;
select * from country where continent='asia';
SELECT * FROM COUNTRY WHERE CONTINENT='ASIA';
SELECT REGION,SUM(POPULATION) FROM COUNTRY GROUP BY REGION  ;
SELECT * FROM COUNTRY WHERE NAME LIKE 'A%';
SELECT * FROM COUNTRY WHERE SURFACEAREA=(SELECT MAX(SURFACEAREA) FROM COUNTRY);
SELECT MIN(POPULATION) FROM COUNTRY;
SELECT GNP FROM COUNTRY WHERE CONTINENT =(SELECT MAX(CONTINENT) FROM COUNTRY);
SELECT * FROM COUNTRY LIMIT 10;
SELECT * FROM COUNTRY WHERE POPULATION = (SELECT MIN(POPULATION ) FROM COUNTRY);
SELECT REGION,SUM(POPULATION) AS MIN_POPULATION FROM COUNTRY GROUP BY REGION ORDER BY MIN_POPULATION ASC;
SELECT NAME,REGION,CONTINENT FROM COUNTRY WHERE SURFACEAREA=(SELECT MAX(SURFACEAREA) FROM COUNTRY) OR POPULATION=(SELECT MAX(POPULATION) FROM COUNTRY);
SELECT * FROM COUNTRY WHERE NAME LIKE 'A__' and length (name)=3;
SELECT LENGTH(NAME) AS LENGTH_LEFT,LEFT(NAME,3) AS FIRSTTHREE FROM COUNTRY;
SELECT * FROM COUNTRY WHERE CONTINENT LIKE 'A___';
SELECT * FROM COUNTRY WHERE GNP='NULL';
use world;
select * from country;
use sakila;
select * from film;
select title from film where rental_duration=(select max(rental_duration) from film);
select  distinct(release_year) from film;
select * from film where LENGTH=(select max(LENGTH) from film);
select * from film where title like 'A%';
SELECT DISTINCT(LANGUAGE_ID) FROM FILM;
SELECT DISTINCT(RENTAL_DURATION) FROM FILM;
SELECT RENTAL_DURATION,TITLE FROM FILM GROUP BY RENTAL_DURATION; /*TASK*/
SELECT * FROM FILM WHERE SPECIAL_FEATURES='DELETED SCENES';
UPDATE FILM SET RELEASE_YEAR=2007 WHERE TITLE='ALASKA PHANTOM';
UPDATE FILM SET TITLE='INDIAN' WHERE TITLE='ALI FOREVER';
SELECT DISTINCT(RATING) FROM FILM;
SELECT RATING,MIN(RENTAL_RATE) AS RENT FROM FILM GROUP BY RATING;
SELECT MAX(RENTAL_RATE) FROM FILM;
SELECT * FROM FILM WHERE TITLE LIKE '_%' AND LENGTH(TITLE)=10; 
SELECT * FROM FILM WHERE TITLE LIKE 'A%' AND LENGTH(TITLE)=5;
SELECT * FROM FILM WHERE LENGTH(TITLE)=10;
SELECT  MIN(RENTAL_DURATION) AS RENT FROM FILM GROUP BY RENT;










